import "../css/style.css";

import { fetchSceneAndMount_simple_scene } from "../polygonjs/scenes/simple_scene/autogenerated/fetchSceneAndMount";

export async function loadScene(){
	return new Promise( async (resolve)=>{
		const loadedData = await fetchSceneAndMount_simple_scene({
			domElement: "app",
			onProgress: (progress) => {
				// console.log(progress)
				if(progress==1){
					const scene = loadedData.scene;
					resolve({scene})
				}
			}
		});
	})
}
