import "./style.css";

import { fetchSceneAndMount_simple_sphere } from "./polygonjs/scenes/simple_sphere/autogenerated/fetchSceneAndMount";

let player;
export async function loadScene(){
	return new Promise( async (resolve)=>{
		const loadedData = await fetchSceneAndMount_simple_sphere({
			domElement: "app",
			onProgress: (progress) => {
				// console.log(progress)
				if(progress==1){
					const scene = loadedData.scene;
					player = scene.threejsScene().getObjectByName('player');
					// console.log('player', player);
					resolve({scene, player})
				}
			}
		});
	})
}
